// <auto-generated />
namespace build2018_mycircle.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddColorField : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddColorField));
        
        string IMigrationMetadata.Id
        {
            get { return "201804102023207_AddColorField"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
